// Cached answers for the demo question, generated by scripts/build-ask-cache.mts through the same
// chain and the same citation check. Never written by hand.
import cacheFile from "@/data/ask-cache.json";
import { normalizeQuestion, type CachedAnswer } from "./chain";

const entries = (cacheFile as { answers: CachedAnswer[] }).answers;

export function cachedAnswer(slug: string, question: string): CachedAnswer | null {
  const q = normalizeQuestion(question);
  return entries.find((e) => e.slug === slug && normalizeQuestion(e.question) === q) ?? null;
}
