// Grading guidance for each criterion, written from docs/PRD.md "Grading system: On paper".
// Scores: 0 not addressed, 1 mentioned but vague or optional ("may"), 2 explicit and binding ("will", "must").
// Ids and labels match the criteria table seeded in supabase/migrations.
export const PROMPT_VERSION = "2026-10-01.1";

export const RUBRIC: { id: string; category: string; label: string; guide: string }[] = [
  { id: "AC-1", category: "Accessible", label: "Stand-alone policy, not run through the student code of conduct",
    guide: "2 if this is a dedicated sexual violence/misconduct policy whose own process governs reports. 1 if it exists but sends reports through the general student code of conduct or another general process. 0 if there is no stand-alone policy." },
  { id: "AC-2", category: "Accessible", label: "Publicly posted and easy to find",
    guide: "2 if the policy text itself commits to being publicly available (e.g. posted on the website). 1 if publication is mentioned vaguely. 0 if not mentioned." },
  { id: "AC-3", category: "Accessible", label: "Plain-language reporting steps",
    guide: "2 if it sets out clear, concrete steps for how to disclose or report (who to contact and how). 1 if reporting is mentioned without clear steps. 0 if not addressed." },
  { id: "SR-1", category: "Survivor rights", label: "No questions about sexual history",
    guide: "2 if it states that a complainant's past sexual history will not be raised, asked about, or considered. 1 if limited or discretionary. 0 if not addressed." },
  { id: "SR-2", category: "Survivor rights", label: "Protection from face-to-face contact",
    guide: "2 if it guarantees the complainant will not have to face the respondent directly (e.g. no direct cross-examination, separate meetings). 1 if only possible or at discretion. 0 if not addressed." },
  { id: "SR-3", category: "Survivor rights", label: "No gag orders",
    guide: "2 if it states complainants are not required to stay silent (no non-disclosure agreements imposed on them) or are free to speak about their own experience. 1 if confidentiality expectations are limited but unclear. 0 if not addressed, or if it requires complainants to keep the matter confidential." },
  { id: "SR-4", category: "Survivor rights", label: "Choice of institutional and external processes",
    guide: "2 if it states the person can choose the institutional process, police/criminal process, both, or neither, and that the choice is theirs. 1 if options are mentioned without the right to choose. 0 if not addressed." },
  { id: "SR-5", category: "Survivor rights", label: "Amnesty for drug or alcohol use when reporting",
    guide: "2 if it states people reporting will not be disciplined for drug or alcohol use or related policy breaches at the time. 1 if amnesty is discretionary. 0 if not addressed." },
  { id: "PR-1", category: "Process", label: "Reasonable, binding timelines",
    guide: "2 if it sets specific binding timelines (benchmark: a complaint process within 45 days and immediate accommodations within 48 hours). 1 if timelines are vague ('timely', 'as soon as possible') or optional. 0 if not addressed." },
  { id: "PR-2", category: "Process", label: "Interim protections (class, residence, work changes)",
    guide: "2 if it commits to interim measures such as changes to classes, residence, or work while a matter is open. 1 if they are possible but discretionary. 0 if not addressed." },
  { id: "PR-3", category: "Process", label: "Covers co-op, internships, work placements",
    guide: "2 if its scope explicitly includes co-op, practicum, internship, or work placement settings. 1 if off-campus activities are covered only generally. 0 if not addressed." },
  { id: "AB-1", category: "Accountability", label: "Survivor told the outcome",
    guide: "2 if it commits to informing the complainant of the outcome, including any sanction or measures relevant to them. 1 if informing them is discretionary or limited. 0 if not addressed." },
  { id: "AB-2", category: "Accountability", label: "Public annual reporting of numbers",
    guide: "2 if it commits to publishing annual numbers (disclosures, reports, outcomes). 1 if reporting is internal only or vague. 0 if not addressed." },
  { id: "AB-3", category: "Accountability", label: "Policy reviewed every 2 years",
    guide: "2 if it requires review at least every 2 years. 1 if review is required on a longer cycle (e.g. every 3 years) or without a stated interval. 0 if not addressed." },
  { id: "AB-4", category: "Accountability", label: "At least 30% student representation on policy committees",
    guide: "2 if it requires students to make up at least 30% of the committee that reviews the policy. 1 if student consultation or membership is required without that share. 0 if not addressed." },
  { id: "TR-1", category: "Training", label: "Mandatory trauma-informed training for decision-makers",
    guide: "2 if it requires trauma-informed training for investigators or decision-makers. 1 if training is mentioned without being required or without being trauma-informed. 0 if not addressed." },
  { id: "TR-2", category: "Training", label: "Prevention education for students",
    guide: "2 if it commits to prevention education or programming for students. 1 if mentioned vaguely. 0 if not addressed." },
];
