// Precomputes the BC dotted silhouette for the homepage hero and the sign-in backdrop: an even grid of
// dots over BC's real outline (Natural Earth 1:50m, data/geo/bc.json), cropped to the PRD's bounds
// (latitude 48.2 to 57.0, longitude -132.0 to -114.0), and every school's real coordinates in the same units.
// Longitude is scaled by cos(52.6 N), the middle of the crop, so the province isn't stretched sideways.
// Output: public/bc-land.svg (the land dots as one static file, drawn through a CSS mask in the theme's
// colour, so page HTML never carries thousands of circles) and lib/bc-dots.json (size and school spots).
// Usage: npm run build:bc-dots   (rerun when data/institutions.json coordinates change)
import { readFileSync, writeFileSync } from "node:fs";

const LAT = { min: 48.2, max: 57.0 }, LNG = { min: -132.0, max: -114.0 };
const K = 10; // units per degree of latitude
const COS = Math.cos((((LAT.min + LAT.max) / 2) * Math.PI) / 180);
const W = Math.round((LNG.max - LNG.min) * COS * K * 10) / 10, H = Math.round((LAT.max - LAT.min) * K);
const STEP = 0.9; // spacing between dots, in units
const x = (lng: number) => (lng - LNG.min) * COS * K;
const y = (lat: number) => (LAT.max - lat) * K;
const r2 = (n: number) => Math.round(n * 100) / 100;

const bc = JSON.parse(readFileSync(new URL("../data/geo/bc.json", import.meta.url), "utf8")) as { coordinates: number[][][][] };
// Ray casting over every ring (outer rings and holes alike, so lakes and holes come out right).
const rings = bc.coordinates.flat();
function inBC(lng: number, lat: number) {
  let inside = false;
  for (const ring of rings) {
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [xi, yi] = ring[i], [xj, yj] = ring[j];
      if (yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
    }
  }
  return inside;
}

const points: [number, number][] = [];
for (let py = STEP / 2; py < H; py += STEP) {
  for (let px = STEP / 2; px < W; px += STEP) {
    const lat = LAT.max - py / K, lng = LNG.min + px / (COS * K);
    if (inBC(lng, lat)) points.push([r2(px), r2(py)]);
  }
}

const { institutions } = JSON.parse(readFileSync(new URL("../data/institutions.json", import.meta.url), "utf8")) as { institutions: { slug: string; lat: number; lng: number }[] };
const schools = institutions.map((i) => ({ slug: i.slug, x: r2(x(i.lng)), y: r2(y(i.lat)) }));

const d = points.map(([px, py]) => `M${px} ${py}h0`).join("");
writeFileSync(new URL("../public/bc-land.svg", import.meta.url),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><path d="${d}" stroke="#000" stroke-width="${STEP * 0.5}" stroke-linecap="round"/></svg>\n`);
writeFileSync(new URL("../lib/bc-dots.json", import.meta.url), JSON.stringify({
  _about: "Generated by scripts/build-bc-dots.mts from data/geo/bc.json (Natural Earth) and data/institutions.json. The land dots are in public/bc-land.svg.",
  width: W, height: H, schools,
}));
console.log(`${points.length} land dots on a ${W} x ${H} grid, ${schools.length} schools`);
