// Precomputes the homepage hero's dotted map: the Vancouver region (Whistler down to the US border, Victoria
// across to the Fraser Valley) from BC's detailed outline (Natural Earth 1:10m, data/geo/bc-vancouver.json),
// plus a natural scatter of decorative "school" dots on land in the map's colours. The decorative dots are
// a preview of the map's look, not real schools. Longitude is scaled by cos(latitude) so nothing stretches.
// Output: public/hero-land.svg (land dots, used as a CSS mask) and lib/hero-dots.json (size and spots).
// Usage: npm run build:hero-dots
import { readFileSync, writeFileSync } from "node:fs";

const LAT = { min: 48.25, max: 50.4 }, LNG = { min: -124.7, max: -121.2 };
const K = 40; // units per degree of latitude
const COS = Math.cos((((LAT.min + LAT.max) / 2) * Math.PI) / 180);
const W = Math.round((LNG.max - LNG.min) * COS * K), H = Math.round((LAT.max - LAT.min) * K);
const STEP = 0.58;
const r2 = (n: number) => Math.round(n * 100) / 100;

const geo = JSON.parse(readFileSync(new URL("../data/geo/bc-vancouver.json", import.meta.url), "utf8")) as { coordinates: number[][][][] };
// BC stops at the 49th parallel, which left a hard straight edge across the bottom right. The land south of
// it (Washington's mainland from Blaine down past Mount Vernon, and the tip of the Olympic Peninsula) is
// added as a rough coastline, so the dots carry on as ground. Decorative only.
const US_LAND: number[][][] = [
  [[-122.76, 49.0], [-121.0, 49.0], [-121.0, 48.0], [-122.36, 48.0], [-122.4, 48.25], [-122.53, 48.42], [-122.48, 48.6],
    [-122.5, 48.75], [-122.62, 48.85], [-122.76, 49.0]],
  [[-125.0, 48.4], [-124.72, 48.39], [-124.6, 48.37], [-124.2, 48.25], [-123.9, 48.16], [-123.4, 48.12], [-122.9, 48.08],
    [-122.9, 48.0], [-125.0, 48.0], [-125.0, 48.4]],
];
const rings = [...geo.coordinates.flat(), ...US_LAND];
function onLand(lng: number, lat: number) {
  let inside = false;
  for (const ring of rings) {
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [xi, yi] = ring[i], [xj, yj] = ring[j];
      if (yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
    }
  }
  return inside;
}
const toLngLat = (x: number, y: number) => [LNG.min + x / (COS * K), LAT.max - y / K];

const land: [number, number][] = [];
const bcLand: [number, number][] = []; // the decorative spots stay in BC
for (let y = STEP / 2; y < H; y += STEP) for (let x = STEP / 2; x < W; x += STEP) {
  const [lng, lat] = toLngLat(x, y);
  if (onLand(lng, lat)) { land.push([r2(x), r2(y)]); if (lat >= 49) bcLand.push([r2(x), r2(y)]); }
}

// Decorative dots: a seeded scatter on land, kept a few units apart, mostly toward the middle (the edges
// fade out). Colours preview the map: teal (aligned), amber (some gap), red (big gap), grey (no policy).
let seed = 20261003;
const rand = () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; };
const COLORS: [string, number][] = [["brand", 0.34], ["some-gap", 0.3], ["big-gap", 0.14], ["no-policy", 0.22]];
const pickColor = () => { let x = rand(); for (const [c, p] of COLORS) { if ((x -= p) < 0) return c; } return "brand"; };
const spots: { x: number; y: number; color: string }[] = [];
for (let tries = 0; spots.length < 46 && tries < 20000; tries++) {
  const [x, y] = bcLand[Math.floor(rand() * bcLand.length)];
  const centred = Math.hypot((x - W / 2) / (W / 2), (y - H / 2) / (H / 2));
  if (centred > 0.9 || rand() < centred * 0.6) continue;
  if (spots.some((s) => Math.hypot(s.x - x, s.y - y) < 5)) continue;
  spots.push({ x, y, color: pickColor() });
}

const d = land.map(([x, y]) => `M${x} ${y}h0`).join("");
writeFileSync(new URL("../public/hero-land.svg", import.meta.url),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><path d="${d}" stroke="#000" stroke-width="${STEP * 0.45}" stroke-linecap="round"/></svg>\n`);
writeFileSync(new URL("../lib/hero-dots.json", import.meta.url), JSON.stringify({
  _about: "Generated by scripts/build-hero-dots.mts from data/geo/bc-vancouver.json (Natural Earth). Decorative spots, not real schools. The land dots are in public/hero-land.svg.",
  width: W, height: H, spots,
}));
console.log(`${land.length} land dots on ${W} x ${H}, ${spots.length} decorative spots`);
