// Precomputes the BC dotted map (svg-dotted-map, cropped to the PRD's bounds: latitude 48.2 to 57.0,
// longitude -132.0 to -114.0) and snaps every school's real coordinates onto the dot grid.
// Output: lib/bc-dots.json, used by the sign-in backdrop and the homepage hero.
// Usage: npm run build:bc-dots   (rerun when data/institutions.json coordinates change)
import { readFileSync, writeFileSync } from "node:fs";
import { createMap } from "svg-dotted-map";

const W = 180, H = 88;
const region = { lat: { min: 48.2, max: 57.0 }, lng: { min: -132.0, max: -114.0 } };
const { institutions } = JSON.parse(readFileSync(new URL("../data/institutions.json", import.meta.url), "utf8"));
const map = createMap({ width: W, height: H, region, mapSamples: 3000 });
const r = (n: number) => Math.round(n * 100) / 100;
const schools = map.addMarkers(institutions.map((i: { slug: string; lat: number; lng: number }) => ({ lat: i.lat, lng: i.lng, slug: i.slug })))
  .map((m) => ({ slug: (m as unknown as { slug: string }).slug, x: r(m.x), y: r(m.y) }));
writeFileSync(new URL("../lib/bc-dots.json", import.meta.url), JSON.stringify({
  _about: "Generated by scripts/build-bc-dots.mts from svg-dotted-map land data and data/institutions.json coordinates.",
  width: W, height: H, points: map.points.map((p) => [r(p.x), r(p.y)]), schools,
}));
console.log(`${map.points.length} land dots, ${schools.length} schools`);
