-- Rubric v2 scoring guides (lib/grading/rubric.ts, approved by Farnaz Oct 4, 2026) in the criteria table, so the
-- database, the grader and the live judge grader read the same words. Ids, labels and categories are unchanged.
update public.criteria set description = '2 if this is a dedicated sexual violence policy whose own process governs reports, independent of the general student code of conduct. 1 if a dedicated policy exists but sends some or all reports through the general code of conduct or another general process, or its own coverage is permissive. 0 if there is no stand-alone policy.' where id = 'AC-1';
update public.criteria set description = '2 if the text commits, in binding language, to the policy being publicly available, for example posted on the institution''s website. 1 if publication is mentioned vaguely or permissively, for example available on request. 0 if not mentioned.' where id = 'AC-2';
update public.criteria set description = '2 if it sets out clear steps to disclose or report: who to contact by role or office, how, and what happens next, stated as the defined process. 1 if reporting is mentioned with incomplete or vague steps, or steps left to discretion. 0 if not addressed.' where id = 'AC-3';
update public.criteria set description = '2 if it states, in binding language, that the complainant''s past sexual history will not be asked about, raised, or considered. 1 if the protection exists but is discretionary, limited, or full of exceptions. 0 if not addressed.' where id = 'SR-1';
update public.criteria set description = '2 if it guarantees the complainant will not have to face the respondent: no direct cross-examination, separate or remote proceedings as a right. 1 if the protection is possible or arranged at discretion, for example where practicable. 0 if not addressed.' where id = 'SR-2';
update public.criteria set description = '2 if it states outright that complainants are not required to sign a non-disclosure agreement or stay silent, and are free to speak about their own experience; an NDA only at the complainant''s own request still counts. 1 if confidentiality expectations are limited but unclear, or silence protections are permissive. 0 if not addressed, or if it requires complainants to keep the matter confidential.' where id = 'SR-3';
update public.criteria set description = '2 if it states the choice is the person''s: the institutional process, the police or criminal process, both, or neither, in binding language that the institution honours it and never requires a police report. 1 if options are mentioned without the right to choose, or the right is hedged by broad institutional overrides. 0 if not addressed.' where id = 'SR-4';
update public.criteria set description = '2 if it commits, in binding language, that a person who reports will not be disciplined for drug or alcohol use, or related breaches, around the time of the incident. 1 if amnesty is discretionary or conditional, for example case by case. 0 if not addressed.' where id = 'SR-5';
update public.criteria set description = '2 if it sets specific binding timelines that meet or beat the benchmark: the complaint process inside 45 days and immediate accommodations inside 48 hours. 1 if timelines are vague (timely, as soon as possible), permissive, or specific but slower than the benchmark. 0 if not addressed.' where id = 'PR-1';
update public.criteria set description = '2 if the institution commits, in binding language, to interim measures while a matter is open, naming what can change: classes, residence, work arrangements. 1 if interim measures are possible but discretionary (may include, as appropriate), or named without a commitment. 0 if not addressed.' where id = 'PR-2';
update public.criteria set description = '2 if the scope names co-op, practicum, internship or work placement settings explicitly, as a binding scope statement. 1 if off-campus activity is covered only in general terms, or the named settings are covered permissively. 0 if not addressed.' where id = 'PR-3';
update public.criteria set description = '2 if it commits, in binding language, to telling the complainant the outcome, including any sanction or measure that affects them. 1 if informing them is discretionary, partial, or hedged without specifics. 0 if not addressed.' where id = 'AB-1';
update public.criteria set description = '2 if it commits, in binding language, to publishing annual numbers: disclosures, reports, outcomes. 1 if reporting is internal only, vague about numbers, or permissive. 0 if not addressed.' where id = 'AB-2';
update public.criteria set description = '2 if it requires review at least every 2 years, in binding language. 1 if review is required on a longer cycle, or with no stated interval, or permissive. 0 if not addressed.' where id = 'AB-3';
update public.criteria set description = '2 if it requires students to make up at least 30% of the committee that reviews the policy. 1 if student membership or consultation is required without that share, or the share is stated permissively. 0 if not addressed.' where id = 'AB-4';
update public.criteria set description = '2 if it requires investigators and decision-makers to complete trauma-informed training, in binding language. 1 if training is mentioned without being required, required but not trauma-informed, or advisory (should). 0 if not addressed.' where id = 'TR-1';
update public.criteria set description = '2 if the institution commits, in binding language, to prevention education or programming for students. 1 if mentioned aspirationally or permissively (endeavour to, aim to, may offer). 0 if not addressed.' where id = 'TR-2';
